
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 16 23:24:55 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 29;
  public static final int DIVIDER = 37;
  public static final int INCREMENT = 23;
  public static final int CONST = 7;
  public static final int EQUALS = 8;
  public static final int NAMESPACE = 5;
  public static final int RSQUAREB = 12;
  public static final int NUMCONST = 45;
  public static final int LPAREN = 13;
  public static final int CONTINUE = 17;
  public static final int FOR = 43;
  public static final int MINUS = 33;
  public static final int DECREMENT = 24;
  public static final int STATIC = 42;
  public static final int RPAREN = 14;
  public static final int SEMICOLON = 9;
  public static final int AND = 26;
  public static final int EQUALTO = 27;
  public static final int LESSTHAN = 31;
  public static final int OR = 25;
  public static final int COMMA = 6;
  public static final int CLASS = 40;
  public static final int PLUS = 39;
  public static final int IF = 21;
  public static final int DOT = 35;
  public static final int MULTIPLIER = 36;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int MODULO = 38;
  public static final int IDENT = 46;
  public static final int BREAK = 16;
  public static final int VOID = 15;
  public static final int RCURLYB = 4;
  public static final int LCURLYB = 3;
  public static final int ARROW = 44;
  public static final int LSQUAREB = 11;
  public static final int COLON = 10;
  public static final int ELSE = 22;
  public static final int READ = 20;
  public static final int CHARCONST = 47;
  public static final int NOTEQUALTO = 28;
  public static final int LESSTHANEQ = 32;
  public static final int BOOLCONST = 48;
  public static final int EXTENDS = 41;
  public static final int PROG = 2;
  public static final int GREATERTHANEQ = 30;
  public static final int PRINT = 19;
}

